### PR TITLE
Branch remove

### LINKED ISSUE #28: Create a RemoveCommand Class and a RemoveChecker Class
The RemoveCommand class should be able to remove a meal from the _user's meal list_, while the RemoveChecker class ensures that the parameters entered are valid, throwing exceptions if they are not.

### PR DESCRIPTION
**Pull request by wentuoc**
Add functionality to remove a meal _from the user's meal list_, through a `RemoveCommand` class and `RemoveChecker` class (that checks that the input is valid, i.e. the index exists and can be parsed into an integer)

Add methods in `MealList` to remove a meal, complete with checks to ensure that the provided index is within the size of the list.

Create new exception classes that document errors resulting from the above actions.

Closes #28

### CODE REVIEW

File: src/main/java/seedu/meallist/MealList.java [hunk 1]
```diff
@@ -32,4 +33,21 @@ public void checkDuplicateMeal(Meal newMeal) throws EZMealPlanException {
         }
     }
 
+    /**
+     * Removes the meal at a specified index and returns it.
+     */
+    public Meal removeMeal(int index) throws EZMealPlanException {
+        try {
+            return mealList.remove(index - 1);
+        } catch (IndexOutOfBoundsException e) {
```
Comment (Teng-Yong-Quan) [inline src/main/java/seedu/meallist/MealList.java:42]: Replace e with IndexOutOfBoundsException

File: src/main/java/seedu/meallist/MealList.java [hunk 2]
```diff
@@ -32,4 +33,21 @@ public void checkDuplicateMeal(Meal newMeal) throws EZMealPlanException {
         }
     }
 
+    /**
+     * Removes the meal at a specified index and returns it.
+     */
+    public Meal removeMeal(int index) throws EZMealPlanException {
+        try {
+            return mealList.remove(index - 1);
```
Comment (Teng-Yong-Quan) [inline src/main/java/seedu/meallist/MealList.java:41]: avoid magic literals: index -1

File: src/main/java/seedu/command/RemoveCommand.java [hunk 3]
```diff
@@ -0,0 +1,41 @@
...
+    public void execute(MealManager mealManager, UserInterface ui) throws EZMealPlanException {
+        MealList userMealList = mealManager.getUserList();
+
+        boolean isValidUserInput = checkValidUserInput();
+        if (!isValidUserInput) {
+            logger.severe("Huge issue detected! The user input format remains invalid despite " +
+                    "passing all the checks for input formatting error.");
+        }
+        assert isValidUserInput;
+        int index = Integer.parseInt(validUserInput.split("\\s+")[1]);
```
Comment (Teng-Yong-Quan) [inline src/main/java/seedu/command/RemoveCommand.java:30]: avoid magic literals: [1]

File: src/main/java/seedu/checkers/RemoveChecker.java [hunk 4]
```diff
@@ -0,0 +1,39 @@
...
+        try {
+            Integer.parseInt(input);
+        } catch (NumberFormatException e) {
+            throw new RemoveFormatException(userInput);
+        }
+    }
+
+    private String extractIndex(String input) throws EZMealPlanException {
+        try {
+            return input.split("\\s+")[1];
```
Comment (Teng-Yong-Quan) [inline src/main/java/seedu/checkers/RemoveChecker.java:33]: Avoid magic literal: [1]

File: src/main/java/seedu/checkers/RemoveChecker.java [hunk 5]
```diff
@@ -0,0 +1,39 @@
...
+        logger.fine("Checking '" + userInput + "' for errors.");
+        String indexString = extractIndex(userInput);
+        parseIndex(indexString);
+        setPassed(true);
+    }
+
+    private void parseIndex(String input) throws EZMealPlanException {
+        try {
+            Integer.parseInt(input);
+        } catch (NumberFormatException e) {
```
Comment (Teng-Yong-Quan) [inline src/main/java/seedu/checkers/RemoveChecker.java:26]: Replace e with numberFormatException

**Review by Teng-Yong-Quan — APPROVED** [review]
